
export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_USER_REGISTRATION = "PAGE_USER_REGISTRATION";


export const PAGE_HOME = "PAGE_HOME";
export const PAGE_PRODUCT_DETAILS = "PAGE_PRODUCT_DETAILS";