
export const STATUS_TYPE_INFO = "STATUS_TYPE_INFO";
export const STATUS_TYPE_SUCCESS = "STATUS_TYPE_SUCCESS";
export const STATUS_TYPE_WARNNG = "STATUS_TYPE_WARNNG";
export const STATUS_TYPE_ERROR = "STATUS_TYPE_ERROR";
